version = 0.1

[default.deploy.parameters]
stack_name = "lostbot-pilot"
resolve_s3 = true
s3_prefix = "lostbot-pilot"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "Stage=dev"
image_repositories = []

[default.build.parameters]
use_container = false
parallel = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"
